esphome:
  name: bombariego
  friendly_name: BombaRiego

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4flsRW/js2yLqRuMet9F/XstkhOy8W0TwXyGKqddEmM="

ota:
  - platform: esphome
    password: "1f761b8a7ce7137c36f3108badefa387"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.151
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "kLIhBXdLAHUO"

captive_portal:

output:
  - platform: gpio
    id: valve_out_1
    pin: 16 #D0

  - platform: gpio
    id: valve_out_2
    pin: 5 #D1

  - platform: gpio
    id: valve_out_3
    pin: 4 #D2

  - platform: gpio
    id: valve_out_4
    pin: 14 #D5

  - platform: gpio
    id: valve_out_5
    pin: 12 #D6

  - platform: gpio
    id: valve_out_6
    pin: 13 #D7

  - platform: gpio
    id: pump_out
    pin: 15 #D8

  - platform: gpio
    id: gate_out
    pin: 1 #TX
    inverted: false

# ============================================================
# SWITCHES
# ============================================================

switch:
  # ----- VÁLVULAS -----
  - platform: output
    name: "Valvula 1 - Frente"
    id: valve_1
    output: valve_out_1
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  - platform: output
    name: "Valvula 2 - Este"
    id: valve_2
    output: valve_out_2
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  - platform: output
    name: "Valvula 3 - Oeste"
    id: valve_3
    output: valve_out_3
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  - platform: output
    name: "Valvula 4 - Nuevo"
    id: valve_4
    output: valve_out_4
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  - platform: output
    name: "Valvula 5 - Extra 1"
    id: valve_5
    output: valve_out_5
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  - platform: output
    name: "Valvula 6 - Extra 2"
    id: valve_6
    output: valve_out_6
    on_turn_on:
      - switch.turn_on: pump
    on_turn_off:
      - script.execute: check_pump_stop

  # ----- BOMBA -----
  - platform: output
    name: "Bomba Riego"
    id: pump
    output: pump_out
    on_turn_on:
      then:
        - wait_until:
            condition:
              for:
                time: 30sec
                condition: 
                  lambda: |-
                    return id(pump).state == true;
        - lambda: |-
            id(pump).turn_off();
    on_turn_off: 
      then:
        - script.execute: apagar_todas_valvulas
    
button:
  - platform: output
    name: "Portón"
    id: gate_button
    output: gate_out
    duration: 2s   # ⬅️ Pulso de 2 segundos

# ============================================================
# SCRIPTS
# ============================================================

script:
  # Apaga la bomba si NO hay válvulas activas
  - id: check_pump_stop
    then:
      - if:
          condition:
            and:
              - switch.is_off: valve_1
              - switch.is_off: valve_2
              - switch.is_off: valve_3
              - switch.is_off: valve_4
              - switch.is_off: valve_5
              - switch.is_off: valve_6
          then:
            - switch.turn_off: pump
    # apagar todas las valvulas con tiempo maximo de bomba
  - id: apagar_todas_valvulas
    mode: single
    then:
      - switch.turn_off: valve_1
      - switch.turn_off: valve_2
      - switch.turn_off: valve_3
      - switch.turn_off: valve_4
      - switch.turn_off: valve_5
      - switch.turn_off: valve_6


web_server:
  port: 80